name: "premierbloc - Setup"
description: "Sets up your premierbloc context in your GitHub Actions workflow."

inputs:
  bucket:
    description: "The bucket use to store the terraform states files."
    required: true

outputs:
  environment:
    description: "The environment computed from GitHub context."
  application:
    description: "The application name computed from repository."
  tag:
    description: "The tag computed from GitHub context."

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.bucket }}
