name: Setup action workflow

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - name: Setup premierbloc context
        id: setup
        uses: premierbloc/setup@0.0.7

      - name: Get setup outputs
        run: |
          echo "environment=${{ steps.setup.outputs.environment }}"
          echo "application=${{ steps.setup.outputs.application }}"
          echo "tag=${{ steps.setup.outputs.tag }}"
